version: '3.8'

services:
  spring-app:
    build: .
    container_name: loadtest-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
    networks:
      - loadtest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  loadtest-network:
    driver: bridge