global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['loadtest-app:8080']
        labels:
          application: 'loadtest-app'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']